export const ALL_CATEGORY_ONES_REQUEST = 'ALL_CATEGORY_ONES_REQUEST'
export const ALL_CATEGORY_ONES_SUCCESS = 'ALL_CATEGORY_ONES_SUCCESS'
export const ALL_CATEGORY_ONES_FAIL = 'ALL_CATEGORY_ONES_FAIL'

export const CATEGORY_ONE_DETAILS_REQUEST = 'CATEGORY_ONE_DETAILS_REQUEST'
export const CATEGORY_ONE_DETAILS_SUCCESS = 'CATEGORY_ONE_DETAILS_SUCCESS'
export const CATEGORY_ONE_DETAILS_FAIL = 'CATEGORY_ONE_DETAILS_FAIL'

export const NEW_CATEGORY_ONE_REQUEST = 'NEW_CATEGORY_ONE_REQUEST'
export const NEW_CATEGORY_ONE_SUCCESS = 'NEW_CATEGORY_ONE_SUCCESS'
export const NEW_CATEGORY_ONE_RESET = 'NEW_CATEGORY_ONE_RESET'
export const NEW_CATEGORY_ONE_FAIL = 'NEW_CATEGORY_ONE_FAIL'

export const UPDATE_CATEGORY_ONE_REQUEST = 'UPDATE_CATEGORY_ONE_REQUEST'
export const UPDATE_CATEGORY_ONE_SUCCESS = 'UPDATE_CATEGORY_ONE_SUCCESS'
export const UPDATE_CATEGORY_ONE_RESET = 'UPDATE_CATEGORY_ONE_RESET'
export const UPDATE_CATEGORY_ONE_FAIL = 'UPDATE_CATEGORY_ONE_FAIL'

export const DELETE_CATEGORY_ONE_REQUEST = 'DELETE_CATEGORY_ONE_REQUEST'
export const DELETE_CATEGORY_ONE_SUCCESS = 'DELETE_CATEGORY_ONE_SUCCESS'
export const DELETE_CATEGORY_ONE_RESET = 'DELETE_CATEGORY_ONE_RESET'
export const DELETE_CATEGORY_ONE_FAIL = 'DELETE_CATEGORYONE_FAIL'

export const ALL_CATEGORY_TWOS_REQUEST = 'ALL_CATEGORY_TWOS_REQUEST'
export const ALL_CATEGORY_TWOS_SUCCESS = 'ALL_CATEGORY_TWOS_SUCCESS'
export const ALL_CATEGORY_TWOS_FAIL = 'ALL_CATEGORY_TWOS_FAIL'

export const CATEGORY_TWO_DETAILS_REQUEST = 'CATEGORY_TWO_DETAILS_REQUEST'
export const CATEGORY_TWO_DETAILS_SUCCESS = 'CATEGORY_TWO_DETAILS_SUCCESS'
export const CATEGORY_TWO_DETAILS_FAIL = 'CATEGORY_TWO_DETAILS_FAIL'

export const NEW_CATEGORY_TWO_REQUEST = 'NEW_CATEGORY_TWO_REQUEST'
export const NEW_CATEGORY_TWO_SUCCESS = 'NEW_CATEGORY_TWO_SUCCESS'
export const NEW_CATEGORY_TWO_RESET = 'NEW_CATEGORY_TWO_RESET'
export const NEW_CATEGORY_TWO_FAIL = 'NEW_CATEGORY_TWO_FAIL'

export const UPDATE_CATEGORY_TWO_REQUEST = 'UPDATE_CATEGORY_TWO_REQUEST'
export const UPDATE_CATEGORY_TWO_SUCCESS = 'UPDATE_CATEGORY_TWO_SUCCESS'
export const UPDATE_CATEGORY_TWO_RESET = 'UPDATE_CATEGORY_TWO_RESET'
export const UPDATE_CATEGORY_TWO_FAIL = 'UPDATE_CATEGORY_TWO_FAIL'

export const DELETE_CATEGORY_TWO_REQUEST = 'DELETE_CATEGORY_TWO_REQUEST'
export const DELETE_CATEGORY_TWO_SUCCESS = 'DELETE_CATEGORY_TWO_SUCCESS'
export const DELETE_CATEGORY_TWO_RESET = 'DELETE_CATEGORY_TWO_RESET'
export const DELETE_CATEGORY_TWO_FAIL = 'DELETE_CATEGORY_TWO_FAIL'

export const ALL_CATEGORY_THREES_REQUEST = 'ALL_CATEGORY_THREES_REQUEST'
export const ALL_CATEGORY_THREES_SUCCESS = 'ALL_CATEGORY_THREES_SUCCESS'
export const ALL_CATEGORY_THREES_FAIL = 'ALL_CATEGORY_THREES_FAIL'

export const CATEGORY_THREE_DETAILS_REQUEST = 'CATEGORY_THREE_DETAILS_REQUEST'
export const CATEGORY_THREE_DETAILS_SUCCESS = 'CATEGORY_THREE_DETAILS_SUCCESS'
export const CATEGORY_THREE_DETAILS_FAIL = 'CATEGORY_THREE_DETAILS_FAIL'

export const NEW_CATEGORY_THREE_REQUEST = 'NEW_CATEGORY_THREE_REQUEST'
export const NEW_CATEGORY_THREE_SUCCESS = 'NEW_CATEGORY_THREE_SUCCESS'
export const NEW_CATEGORY_THREE_RESET = 'NEW_CATEGORY_THREE_RESET'
export const NEW_CATEGORY_THREE_FAIL = 'NEW_CATEGORY_THREE_FAIL'

export const UPDATE_CATEGORY_THREE_REQUEST = 'UPDATE_CATEGORY_THREE_REQUEST'
export const UPDATE_CATEGORY_THREE_SUCCESS = 'UPDATE_CATEGORY_THREE_SUCCESS'
export const UPDATE_CATEGORY_THREE_RESET = 'UPDATE_CATEGORY_THREE_RESET'
export const UPDATE_CATEGORY_THREE_FAIL = 'UPDATE_CATEGORY_THREE_FAIL'

export const DELETE_CATEGORY_THREE_REQUEST = 'DELETE_CATEGORY_THREE_REQUEST'
export const DELETE_CATEGORY_THREE_SUCCESS = 'DELETE_CATEGORY_THREE_SUCCESS'
export const DELETE_CATEGORY_THREE_RESET = 'DELETE_CATEGORY_THREE_RESET'
export const DELETE_CATEGORY_THREE_FAIL = 'DELETE_CATEGORY_THREE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'